version: 2
updates:
  - package-ecosystem: gomod
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
    allow:
      - dependency-type: direct
    target-branch: "dev"
    directory: /
    commit-message:
      prefix: "[deps] ⬆️"
    labels:
      - "dependencies"